Fix increase pylint coverage
maxspahn/gym_envs_urdf pull request #117
Opened 2022-08-23 19:08 UTC by GijsGroote

One thing to dubbel check would be the function add_to_bullet (previously add2Bullet) in  #[5fd84e7](https://github.com/GijsGroote/gym_envs_urdf/commit/5fd84e76932f9b5538ba38aab41e0bc8b01d784e) and that it does not break with the dependency on [the motion planning scenes](https://github.com/maxspahn/motion_planning_scenes).

2022-08-23 21:04 UTC, GijsGroote commented
PR https://github.com/maxspahn/motion_planning_scenes/pull/36 should first be merged before the testing can succeed here

2022-09-12 15:04 UTC, maxspahn requested changes
Great work. I think this is very helpful.
I am open to removing the in-file comments under the condition that motion planning scenes becomes a required dependency. 
Then, we must first resolve the dependency to your develop branch in the pyproject.toml.

2022-09-12 15:04 UTC, maxspahn commented on examples/panda_reacher.py
> +
I know about the drawbacks of in-file imports. However, motion planning scenes and thus all the obstacles and goals are an optional dependency. So either we make it a required dependency or we keep the in-file imports.

2022-09-12 15:04 UTC, maxspahn commented on examples/point_robot.py
> +from examples.scene_objects.obstacles import (
same as above

2022-09-12 15:04 UTC, maxspahn commented on pyproject.toml
> +motion-planning-scenes = {git="https://github.com/GijsGroote/motion_planning_scenes.git",  rev='gijs_develop'}
We must merge the differences between your develop branch and the current version before we can merge this.

2022-09-12 15:04 UTC, maxspahn commented on urdfenvs/urdfCommon/urdf_env.py
> +            self, robot: GenericRobot, flatten_ob: bool = False,
What is the benefit of abbreviating the argument?

2022-09-21 12:05 UTC, maxspahn commented on pyproject.toml
> +motion-planning-scenes = {git="https://github.com/GijsGroote/motion_planning_scenes.git",  rev='gijs_develop'}
@GijsGroote Is this change really needed? Otherwise, we could merge this PR without having to wait for the developments on motion_planning_scenes.

2022-09-21 12:34 UTC, closed without merging