➕ Added Docs for WSL2 + vcXsrv
maxspahn/gym_envs_urdf pull request #178
Opened 2023-04-14 11:26 UTC by behradkhadem

Hello Max! 
I added some docs for using package inside Windows and circumvent issues with Visual Studio C++ stuff for using PyBullet. (Issued here: https://github.com/maxspahn/gym_envs_urdf/issues/137) I tried to be as clear and concise as possible. If you think there is room for improving, I'm glad to help. 

And also sorry for the delay, things got out of hand here.

2023-04-15 18:19 UTC, maxspahn requested changes
:fire: Thanks a lot @behradkhadem . That should make of windows users easier. 

I added two comments, maybe you can integrate them.

2023-04-15 18:19 UTC, maxspahn commented on docs/source/windows.rst
> +WSL2 with vcXsrv
Can you make the heading more explicit, so that we avoid abberviations in the heading. Maybe simple `using windows subsystem linux`.

2023-04-15 18:19 UTC, maxspahn commented on docs/source/windows.rst
> +.. image:: https://user-images.githubusercontent.com/31148015/227963709-b527d1db-2eee-4b0b-9ecd-f2d722ee2382.png
Can you maybe add this picture in othe repository. Ideally, in the `docs/source/img` folder.

2023-04-15 18:20 UTC, maxspahn commented
Also relevant for #59

2023-04-16 13:37 UTC, behradkhadem commented
Done and done!

2023-04-17 07:38 UTC, merged