Ft automated extraction joint
maxspahn/gym_envs_urdf pull request #91
Opened 2022-04-29 00:17 UTC by SkyloveQiu

The first version is finished, resolve #57.
There are a few problems, to make the extraction of id, I introduce preload idea which means loading the robot before generating the environment. 
I have noticed that the preload will slow down the start-up process.

2022-04-29 00:21 UTC, SkyloveQiu commented
The code needs to clean up, this pr just for testing purposes.

2022-04-29 06:55 UTC, maxspahn reviewed
Great initiative on this issue! It is not a simple one.

The goal of this PR is to replace hard-coded joint indices by hard-coded joint names. 
That is more intuitive and less prone to errors caused by changes in the urdf-file. 
The idea is to set the actuated joint names for every robot, similar to what you did in the tiago-robot. Then there should be a extractor function in the generic robot probably that takes these joint names and maps them to the correct indices. These indices can then be processed as done previously. 

Let me know if you have additional questions.

2022-04-29 06:55 UTC, maxspahn commented on urdfenvs/tiago_reacher/resources/tiago_robot.py
> +                self._castor_joints.append(index)
That doesn't look too bad. I think you understood the idea behind it.
I will comment a bit more in the comment on this PR.

2022-04-29 06:55 UTC, maxspahn commented on urdfenvs/urdfCommon/differential_drive_robot.py
> +        self.preload()
The preloading does not relate to the observation space so it should not be called inside this particular function but rather in either the constructor or the reset function.

2022-04-29 13:43 UTC, SkyloveQiu commented
preload has been removed. I changed the order of `set_space`, I moved it to the end of reset()

2022-04-29 14:05 UTC, SkyloveQiu commented
How do I classify the joints? currently I use name to classify it, is there anyway to automate this process?

2022-05-02 11:50 UTC, SkyloveQiu commented
I have updated the function `get_indexed_joint_info` in `genetic_robot`, now the function will use `_joint_names` to update `_robot_joints` and `_castor_joints`.

2022-05-03 22:46 UTC, SkyloveQiu commented
the bug is observed, other robots have different start-up procedures compared to Tiago robots

2022-05-04 07:14 UTC, maxspahn commented
You can also test your changes locally using `pytest`

2022-05-05 01:28 UTC, SkyloveQiu commented
The bug is found, for point robot, it adds a lidar sensor after, in the previous design that reset will call `set_space` function which will remove lidar sensor space which causes an error. The pytest passed with warnings on my machine but it may different on CI.

2022-05-06 19:33 UTC, maxspahn requested changes
I will verify it on my system.
Can you still remove all the debug printout statements?

2022-05-06 19:33 UTC, maxspahn commented on examples/point_robot.py
> +        print(ob)
Can you remove all debug-print statements?

2022-05-06 19:33 UTC, maxspahn commented on examples/tiago.py
> +    print("resetting")
same here

2022-05-08 01:09 UTC, SkyloveQiu commented
I am not sure how to do the Prius robot, it seems not the same as other robots.

2022-05-08 01:34 UTC, SkyloveQiu commented
it seems one pytest fails, not sure why.

2022-05-08 01:46 UTC, SkyloveQiu commented
All other robots have been updated, and the pytest passed on my machine.

2022-05-08 21:21 UTC, maxspahn requested changes
Can we get rid of the last tiny bit of duplicated code, concerning `self._urdf_joints`

2022-05-08 21:21 UTC, maxspahn commented on urdfenvs/albert_reacher/resources/albert_robot.py
> +        self.get_indexed_joint_info()
Can't we move that to a central function? Currently, these lines are in all the robot files.

2022-05-08 21:21 UTC, maxspahn commented on urdfenvs/albert_reacher/resources/albert_robot.py
>      def set_joint_indices(self):
After your changes, the name of this function needs to be modified to something like `set_joint_names`

2022-05-08 21:21 UTC, maxspahn commented on urdfenvs/urdfCommon/generic_robot.py
>          the correct joint indices for self.setJointIndices.
This function is now central, so the comment on debugging and finding the correct joint indices should be modified.

2022-05-08 21:21 UTC, maxspahn commented on urdfenvs/urdfCommon/generic_robot.py
> +
Concerning the other comment on repeated code lines: This is where I expect self._urdf_joints to be set, just like you do it with the other joint indices.

2022-05-09 07:09 UTC, maxspahn requested changes
Only a minor change to respect.
One function -> one purpose.

2022-05-09 07:09 UTC, maxspahn commented on urdfenvs/albert_reacher/resources/albert_robot.py
> +        self.get_indexed_joint_info()
This function should be called from the generic robot class.

2022-05-10 07:04 UTC, maxspahn approved these changes
Great work.

2022-05-10 07:04 UTC, merged

2022-05-10 07:21 UTC, maxspahn commented
Can you reopen this pull request. I needed to revert it, as there were too many errors which I did not check carefully enough.
Will comment on them in the new PR.

2022-05-10 08:45 UTC, SkyloveQiu commented
The revert is not processed correctly, it shows nothing to compare in my site.

2022-05-10 08:58 UTC, maxspahn commented
You cannot reopen a merged pull-request. I created a new pull request reverting this one.
Now, you should open a new PR from this branch.