Revert "Revert "Ft automated extraction joint""
maxspahn/gym_envs_urdf pull request #95
Opened 2022-05-10 09:08 UTC by SkyloveQiu

Reverts maxspahn/gym_envs_urdf#94

2022-05-10 11:36 UTC, SkyloveQiu commented
The bug is found and a bad solution is found.
This will increase the time complexity of `get_indexed_joint_info` function from O(nlogn) to O(n^2) which doubles the time to start simulation.

2022-05-10 12:57 UTC, maxspahn commented
First comment: There are trailing white spaces and trailing indent everywhere in your code.
This is also reported by the linter. Secondly, it's better to have a working and slow solution than a fast one that does not work.

2022-05-10 13:03 UTC, maxspahn requested changes
Can you please make sure that you remove all white spaces in the files?
Also, some of the introduced lines are very long (> 80 characters). This is reported by the pylinter.
This must also be removed.

2022-05-10 13:03 UTC, maxspahn commented on urdfenvs/urdfCommon/generic_robot.py
> +                    self._robot_joints.append(i)
This double loop seems to be the only solution for now.
The complexity does not matter for the moment.

2022-05-17 06:45 UTC, maxspahn requested changes
I appreciate your effort in fixing line length in other files. Be aware, that this is not part of this issue.
Please remove your visual studio code configuration from the repository.

2022-05-17 06:45 UTC, maxspahn commented on .vscode/settings.json
> +}
This file should not be uploaded to git as it is a config file for one specific editor.

2022-05-17 06:45 UTC, maxspahn commented on urdfenvs/urdfCommon/holonomic_robot.py
> +        "velocity": joint_vel}}
From https://peps.python.org/pep-0008/:
> The preferred way of wrapping long lines is by using Python’s implied line continuation inside parentheses, brackets and braces. Long lines can be broken over multiple lines by wrapping expressions in parentheses. These should be used in preference to using a backslash for line continuation.

> Backslashes may still be appropriate at times. For example, long, multiple with-statements could not use implicit continuation before Python 3.10, so backslashes were acceptable for that case:

2022-05-17 11:44 UTC, maxspahn requested changes
Can you please remove this breaking of lines everywhere?
You can simply use `black` for that.

2022-05-17 11:44 UTC, maxspahn commented on urdfenvs/panda_reacher/resources/panda_robot.py
> +                                            "panda_finger_joint2"]
Still this issue...

2022-05-17 11:44 UTC, maxspahn commented on urdfenvs/mobile_reacher/resources/mobile_robot.py
> +                                    "mobile_joint_theta"]
again

2022-05-17 11:44 UTC, maxspahn commented on urdfenvs/mobile_reacher/resources/mobile_robot.py
> +                                    "mobile_joint_theta"]
again

2022-05-17 11:44 UTC, maxspahn commented on urdfenvs/dual_arm/resources/dual_arm_robot.py
> +                                chain(range(1,4),range(5,7))]
Can you remove this style everywhere?

2022-05-17 12:06 UTC, SkyloveQiu commented on urdfenvs/dual_arm/resources/dual_arm_robot.py
> +                                chain(range(1,4),range(5,7))]
yes, I am searching it.

2022-05-17 12:17 UTC, SkyloveQiu commented
The pylint reports score of 9.91/10.

2022-06-07 12:27 UTC, maxspahn requested changes
Sorry for my late comment on this PR.

I quickly verified the examples. The panda robot is broken by this PR as the ordering of the joints is different that what it used to be. Can you verify this for all the robots?

2022-06-07 12:27 UTC, maxspahn commented on urdfenvs/tiago_reacher/resources/tiago_robot.py
> +            + arm_left_joint_names
This also changes the order of the joints. Please change left and right so that it fits the old ordering.

2022-06-09 12:09 UTC, SkyloveQiu commented
fixed

2022-06-23 11:26 UTC, maxspahn commented
The loading/resetting of the robots was so slow, because of `URDF.load()`. By centralizing it, it is only called once. As a consequence the
joint id extraction does not add any computational costs to the loading.

2022-06-23 13:58 UTC, SkyloveQiu commented
I have run all of the examples, and all of them are working correctly.

2022-07-25 08:38 UTC, maxspahn approved these changes

2022-07-25 08:39 UTC, merged